package com.lambdalab.gradle.tasks

import com.lambdalab.gradle.tasks.thrift.ScroogeCompiler
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.TaskAction

class ThriftScalaCompile extends ThriftCompile {
    String genFileMapPath = "/var/tmp/scrooge-gen-file-map.txt"

    @Input
    @Optional
    def opts = ["--finagle", "--gen-file-map", genFileMapPath]

    @TaskAction
    def compile() {
        ScroogeCompiler.compile(source, output, opts)

        File genFileMap = new File(genFileMapPath)
        if (genFileMap.exists()) {
            String genFileMapContent = genFileMap.text

            project.fileTree(output).each { file ->
                // Delete any generated file that is not in the file map
                if (file.text.contains("Generated by Scrooge") && !genFileMapContent.contains(file.absolutePath)) {
                    println("Delete stale generated scala file '$file.absolutePath'")
                    file.delete()
                }
            }
            genFileMap.delete()

        } else {
            println("Gen file map doesn't existed!")
        }
    }
}
